---

# Exit process immediately if the Cassandra data directory exists on any node (don't want to overwrite a running system !)
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
  - { role: dse_test_for_data_directory }

  
# Get the current timestamp and register datastax debian packages
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Get the current timestamp
    shell: 'date +%Y%m%d%H%M%S'
    register: current_timestamp
  roles:
  - { role: datastax_pkg }


# Install and configure DSE
# Seed list is built as nodes are added (see role: dse_common)
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: java8_inst }
    - { role: dse_osparam_change }
    - { role: dse_osparam_ssd_change, when: is_ssd_storage | bool }
    - { role: dse_common }
    - { role: dse_instbin }
    - { role: dse_updcfg }
